const FIGURES = [
  {
    category: "integrated",
    group: "통합",
    title: "성남시 행정동 Type Label 지도",
    path: "../analysis/figures/seongnam_type_label_map.png",
    description: "주거·노동·교통 3-axis 통합 점수로 분류한 Type A-D 지도와 구 경계.",
  },
  {
    category: "residential",
    group: "주거 인사이트",
    title: "주거 데이터 핵심 인사이트",
    path: "../residential/data/processed/python_visualizations/15_insight_executive_summary.png",
    description: "성남시 주거 분석의 핵심 메시지를 6개 카드로 요약.",
  },
  {
    category: "residential",
    group: "주거 인사이트",
    title: "행정동 수요 포지셔닝",
    path: "../residential/data/processed/python_visualizations/16_insight_admin_dong_quadrants.png",
    description: "세대수와 생산가능인구 비율로 행정동 수요 성격을 구분.",
  },
  {
    category: "residential",
    group: "주거 인사이트",
    title: "구별 수요-공급-가격 포지셔닝",
    path: "../residential/data/processed/python_visualizations/17_insight_gu_demand_supply_price.png",
    description: "세대수 대비 주택수, 매매가, 아파트 비율을 함께 비교.",
  },
  {
    category: "residential",
    group: "주거 인사이트",
    title: "법정동-건축유형별 가격 상위 조합",
    path: "../residential/data/processed/python_visualizations/18_insight_top_price_combinations.png",
    description: "매매·전세·월세 상위 법정동-건축유형 조합.",
  },
  {
    category: "residential",
    group: "주거 인사이트",
    title: "구별 실거래 거래구분 믹스",
    path: "../residential/data/processed/python_visualizations/19_insight_transaction_mix.png",
    description: "구별 매매·전세·월세 거래 비중과 총 거래건수.",
  },
  {
    category: "residential",
    group: "행정동 수요",
    title: "행정동별 세대수",
    path: "../residential/data/processed/python_visualizations/01_admin_dong_households.png",
    description: "행정동별 세대수 규모를 구별 색상으로 비교.",
  },
  {
    category: "residential",
    group: "행정동 수요",
    title: "세대수와 생산가능인구의 관계",
    path: "../residential/data/processed/python_visualizations/02_admin_households_vs_working_age.png",
    description: "세대 규모와 생산가능인구 규모의 관계, 점 크기는 고령인구 비율.",
  },
  {
    category: "residential",
    group: "지도",
    title: "행정동별 세대수 지도",
    path: "../residential/data/processed/python_visualizations/03_map_admin_households.png",
    description: "행정동별 주거 수요 규모를 지도 위에 표현.",
  },
  {
    category: "residential",
    group: "지도",
    title: "행정동별 생산가능인구 비율",
    path: "../residential/data/processed/python_visualizations/04_map_working_age_ratio.png",
    description: "생산가능인구 비율을 행정동 지도에 표시.",
  },
  {
    category: "residential",
    group: "지도",
    title: "행정동별 65세 이상 인구 비율",
    path: "../residential/data/processed/python_visualizations/05_map_elderly_ratio.png",
    description: "고령인구 비율이 높은 행정동을 지도에서 확인.",
  },
  {
    category: "residential",
    group: "주택 재고",
    title: "구별 주택 재고 구성",
    path: "../residential/data/processed/python_visualizations/06_gu_housing_stock_composition.png",
    description: "구별 주택 유형 구성비를 100% 누적 막대로 비교.",
  },
  {
    category: "residential",
    group: "주택 재고",
    title: "세대수 대비 주택수",
    path: "../residential/data/processed/python_visualizations/07_gu_housing_supply_per_household.png",
    description: "구별 주택수와 세대수의 상대 규모.",
  },
  {
    category: "residential",
    group: "가격 히트맵",
    title: "법정동 x 건축유형 매매가 중앙값",
    path: "../residential/data/processed/python_visualizations/08_legal_dong_sales_price_heatmap.png",
    description: "거래건수 10건 이상 조합의 평당 매매가 중앙값.",
  },
  {
    category: "residential",
    group: "가격 히트맵",
    title: "법정동 x 건축유형 전세보증금 중앙값",
    path: "../residential/data/processed/python_visualizations/09_legal_dong_jeonse_deposit_heatmap.png",
    description: "법정동·건축유형별 평당 전세보증금 수준.",
  },
  {
    category: "residential",
    group: "가격 히트맵",
    title: "법정동 x 건축유형 월세 중앙값",
    path: "../residential/data/processed/python_visualizations/10_legal_dong_monthly_rent_heatmap.png",
    description: "법정동·건축유형별 평당 월세 수준.",
  },
  {
    category: "residential",
    group: "거래",
    title: "구별·건축유형별 거래량",
    path: "../residential/data/processed/python_visualizations/11_transaction_volume_by_gu_and_type.png",
    description: "매매·전세·월세 거래량을 구와 건축유형으로 비교.",
  },
  {
    category: "residential",
    group: "거래",
    title: "건축유형별 매매가 분포",
    path: "../residential/data/processed/python_visualizations/12_sales_price_distribution_by_type.png",
    description: "건축유형별 평당 매매가 분포를 구별로 비교.",
  },
  {
    category: "residential",
    group: "거래",
    title: "월세 거래의 보증금-월세 분포",
    path: "../residential/data/processed/python_visualizations/13_monthly_rent_deposit_scatter.png",
    description: "월세 거래의 보증금과 월세 관계를 산점도로 확인.",
  },
  {
    category: "residential",
    group: "거래",
    title: "실거래 월별 추이",
    path: "../residential/data/processed/python_visualizations/14_monthly_transaction_trends.png",
    description: "월별 매매가 중앙값과 전월세 거래건수 추이.",
  },
  {
    category: "residential",
    group: "기초 주거 figure",
    title: "행정동별 세대수",
    path: "../residential/data/processed/figures/admin_dong_households.png",
    description: "기초 파이프라인 산출물: 행정동별 세대수.",
  },
  {
    category: "residential",
    group: "기초 주거 figure",
    title: "행정동 세대수 vs 생산가능인구",
    path: "../residential/data/processed/figures/admin_dong_households_vs_working_age.png",
    description: "세대수와 생산가능인구의 관계를 기초 산점도로 확인.",
  },
  {
    category: "residential",
    group: "기초 주거 figure",
    title: "행정동별 생산가능인구",
    path: "../residential/data/processed/figures/admin_dong_working_age_population.png",
    description: "행정동별 생산가능인구 절대 규모.",
  },
  {
    category: "residential",
    group: "기초 주거 figure",
    title: "행정동별 생산가능인구 비율",
    path: "../residential/data/processed/figures/admin_dong_working_age_ratio.png",
    description: "행정동별 생산가능인구 비율.",
  },
  {
    category: "residential",
    group: "기초 주거 figure",
    title: "아파트 비율",
    path: "../residential/data/processed/figures/apartment_ratio_by_region.png",
    description: "지역별 아파트 비율.",
  },
  {
    category: "residential",
    group: "기초 주거 figure",
    title: "세대수 vs 아파트수",
    path: "../residential/data/processed/figures/households_vs_apartments.png",
    description: "구별 세대수와 아파트 재고 비교.",
  },
  {
    category: "residential",
    group: "기초 주거 figure",
    title: "세대수 vs 주택 재고",
    path: "../residential/data/processed/figures/households_vs_housing_stock.png",
    description: "구별 세대수와 전체 주택 재고 비교.",
  },
  {
    category: "residential",
    group: "기초 주거 figure",
    title: "세대수 vs 연립·다세대",
    path: "../residential/data/processed/figures/households_vs_rowhouse_multifamily.png",
    description: "구별 세대수와 연립·다세대 재고 비교.",
  },
  {
    category: "residential",
    group: "기초 주거 figure",
    title: "주택 재고 by region",
    path: "../residential/data/processed/figures/housing_stock_by_region.png",
    description: "구별 주택 재고 규모.",
  },
  {
    category: "residential",
    group: "기초 주거 figure",
    title: "세대수 대비 주택 재고",
    path: "../residential/data/processed/figures/housing_stock_per_household.png",
    description: "세대수 대비 주택 재고 수준.",
  },
  {
    category: "residential",
    group: "기초 주거 figure",
    title: "주택 유형 구성",
    path: "../residential/data/processed/figures/housing_type_stacked_bar.png",
    description: "구별 주택 유형 구성비.",
  },
  {
    category: "residential",
    group: "기초 주거 figure",
    title: "전세보증금 평당 중앙값",
    path: "../residential/data/processed/figures/jeonse_price_per_pyeong.png",
    description: "지역별 전세보증금 평당 중앙값.",
  },
  {
    category: "residential",
    group: "기초 주거 figure",
    title: "건축유형별 전세보증금 분포",
    path: "../residential/data/processed/figures/jeonse_price_by_type_boxplot.png",
    description: "건축유형별 전세보증금 분포.",
  },
  {
    category: "residential",
    group: "기초 주거 figure",
    title: "월세 평당 중앙값",
    path: "../residential/data/processed/figures/rent_price_per_pyeong.png",
    description: "지역별 월세 평당 중앙값.",
  },
  {
    category: "residential",
    group: "기초 주거 figure",
    title: "건축유형별 월세 분포",
    path: "../residential/data/processed/figures/rent_price_by_type_boxplot.png",
    description: "건축유형별 월세 분포.",
  },
  {
    category: "residential",
    group: "기초 주거 figure",
    title: "연립·다세대 비율",
    path: "../residential/data/processed/figures/rowhouse_multifamily_ratio_by_region.png",
    description: "구별 연립·다세대 비율.",
  },
  {
    category: "residential",
    group: "기초 주거 figure",
    title: "매매가 평당 중앙값",
    path: "../residential/data/processed/figures/sales_price_per_pyeong.png",
    description: "지역별 매매가 평당 중앙값.",
  },
  {
    category: "residential",
    group: "기초 주거 figure",
    title: "건축유형별 매매가 분포",
    path: "../residential/data/processed/figures/sales_price_by_type_boxplot.png",
    description: "건축유형별 매매가 분포.",
  },
  {
    category: "employment",
    group: "노동",
    title: "구별 종사자 수",
    path: "../business_employment/data/processed/figures/gu_total_workers_bar.png",
    description: "구별 전체 종사자 규모.",
  },
  {
    category: "employment",
    group: "노동",
    title: "구별 종사자 분포",
    path: "../business_employment/data/processed/figures/gu_total_workers_boxplot.png",
    description: "구별 동 단위 종사자 분포.",
  },
  {
    category: "employment",
    group: "노동",
    title: "구별 산업 구성",
    path: "../business_employment/data/processed/figures/gu_industry_stack_bar.png",
    description: "구별 산업 구조를 누적 막대로 비교.",
  },
  {
    category: "employment",
    group: "노동",
    title: "구별 법인 순유입",
    path: "../business_employment/data/processed/figures/gu_corp_net_inflow_bar.png",
    description: "법인 유입과 유출의 순변화를 구별로 비교.",
  },
  {
    category: "employment",
    group: "노동",
    title: "행정동별 종사자 수",
    path: "../business_employment/data/processed/figures/dong_total_workers.png",
    description: "동 단위 일자리 공급 규모.",
  },
  {
    category: "employment",
    group: "노동",
    title: "행정동별 자영업자 비율",
    path: "../business_employment/data/processed/figures/dong_self_employed_ratio.png",
    description: "동별 자영업 중심성을 비교.",
  },
  {
    category: "employment",
    group: "노동",
    title: "행정동별 상용근로자 비율",
    path: "../business_employment/data/processed/figures/dong_regular_worker_ratio.png",
    description: "고용 안정성과 일자리 성격을 동 단위로 비교.",
  },
  {
    category: "employment",
    group: "노동",
    title: "행정동별 IT 법인 비율",
    path: "../business_employment/data/processed/figures/dong_it_corp_ratio.png",
    description: "IT 관련 법인 비중을 동 단위로 비교.",
  },
  {
    category: "employment",
    group: "노동",
    title: "사업체 수와 종사자 수",
    path: "../business_employment/data/processed/figures/scatter_biz_vs_workers.png",
    description: "사업체 규모와 종사자 규모의 관계.",
  },
  {
    category: "transport",
    group: "교통",
    title: "높은 수요·낮은 접근성 Top 10",
    path: "../transport/transport/data/processed/figures/high_demand_low_access_top10.png",
    description: "통근 수요는 크지만 접근성 개선 필요성이 큰 행정동.",
  },
  {
    category: "transport",
    group: "교통",
    title: "통근 수요와 접근성",
    path: "../transport/transport/data/processed/figures/commute_vs_accessibility.png",
    description: "통근 수요와 접근성 점수의 관계.",
  },
  {
    category: "transport",
    group: "교통",
    title: "구별 통행 수단 비중",
    path: "../transport/transport/data/processed/figures/mode_share_by_gu.png",
    description: "구별 지하철·버스·승용차 등 통행 수단 구조.",
  },
];

const LEGACY_RESIDENTIAL_FIGURES = [
  ["admin_dong_households.png", "복제본: 행정동별 세대수"],
  ["admin_dong_households_vs_working_age.png", "복제본: 행정동 세대수 vs 생산가능인구"],
  ["admin_dong_working_age_population.png", "복제본: 행정동별 생산가능인구"],
  ["admin_dong_working_age_ratio.png", "복제본: 행정동별 생산가능인구 비율"],
  ["apartment_ratio_by_region.png", "복제본: 아파트 비율"],
  ["households_vs_apartments.png", "복제본: 세대수 vs 아파트수"],
  ["households_vs_housing_stock.png", "복제본: 세대수 vs 주택 재고"],
  ["households_vs_rowhouse_multifamily.png", "복제본: 세대수 vs 연립·다세대"],
  ["housing_stock_by_region.png", "복제본: 주택 재고 by region"],
  ["housing_stock_per_household.png", "복제본: 세대수 대비 주택 재고"],
  ["housing_type_stacked_bar.png", "복제본: 주택 유형 구성"],
  ["jeonse_price_by_type_boxplot.png", "복제본: 건축유형별 전세보증금 분포"],
  ["jeonse_price_per_pyeong.png", "복제본: 전세보증금 평당 중앙값"],
  ["rent_price_by_type_boxplot.png", "복제본: 건축유형별 월세 분포"],
  ["rent_price_per_pyeong.png", "복제본: 월세 평당 중앙값"],
  ["rowhouse_multifamily_ratio_by_region.png", "복제본: 연립·다세대 비율"],
  ["sales_price_by_type_boxplot.png", "복제본: 건축유형별 매매가 분포"],
  ["sales_price_per_pyeong.png", "복제본: 매매가 평당 중앙값"],
];

LEGACY_RESIDENTIAL_FIGURES.forEach(([filename, title]) => {
  FIGURES.push({
    category: "archive",
    group: "복제본",
    title,
    path: `../transport/residential/data/processed/figures/${filename}`,
    description: "transport/residential 경로에 함께 보관된 주거 figure 복제본.",
  });
});
